service: Users

provider:
  name: aws
  runtime: nodejs4.3
  stage: Dev
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    TABLE_NAME: { Ref: UsersTable }
    TABLE_PREFIX: ${opt:stage, self:provider.stage}-
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  ListUsers:
    handler: users/list.list
    name: ${opt:stage, self:provider.stage}-Users-List
    events:
      - http:
          path: users
          method: get
          cors: true

  ListUsersByGroup:
    handler: users/getByGroup.list
    name: ${opt:stage, self:provider.stage}-Users-ListByGroup
    events:
      - http:
          path: groups/{groupId}/users
          method: get
          cors: true

  CreateUser:
    handler: users/create.post
    name: ${opt:stage, self:provider.stage}-Users-Create
    events:
      - http:
          path: groups/{groupId}/users
          method: post
          cors: true

  UpdateUser:
    handler: users/update.put
    name: ${opt:stage, self:provider.stage}-Users-Update
    events:
      - http:
          path: groups/{groupId}/users/{userId}
          method: put
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${opt:stage, self:provider.stage}-Users'
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  Outputs:
    TableName:
      Description: Name of the users table for this stage
      Value: { Ref: UsersTable }
      Export:
        Name: '${opt:stage, self:provider.stage}-UsersTableName'
    UsersEndpoint:
      Description: Invokable URL for the users serverless API for this stage
      Value:
        Fn::Join:
          - ''
          - - https://
            - Ref: ApiGatewayRestApi
            - .execute-api.us-east-1.amazonaws.com/Dev
      Export:
        Name: '${opt:stage, self:provider.stage}-UsersEndpoint'

package:
  exclude:
    - node_modules/serverless/**
