service: SantaSwap-Serverless

provider:
  name: aws
  runtime: nodejs4.3
  stage: Local
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    GROUPS_TABLE: { Ref: GroupsTable }
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  
  CreateAndJoin:
    handler: groups/createAndJoin.handler
    name: ${opt:stage, self:provider.stage}-Groups-CreateAndJoin
    events:
      - http:
          path: groups
          method: post
          cors: true
  
  Update:
    handler: groups/updateGroup.handler
    name: ${opt:stage, self:provider.stage}-Groups-Update
    events:
      - http:
          path: groups/{groupId}
          method: put
          cors: true
  
  ListByUser:
    handler: groups/listByUser.handler
    name: ${opt:stage, self:provider.stage}-Groups-ListByUser
    events:
      - http:
          path: users/{userId}/groups
          method: get
          cors: true
  
  Get:
    handler: groups/get.handler
    name: ${opt:stage, self:provider.stage}-Groups-Get
    events:
      - http:
          path: groups/{groupId}
          method: get
          cors: true
  
  Join:
    handler: groups/join.handler
    name: ${opt:stage, self:provider.stage}-Groups-Join
    events:
      - http:
          path: groups/{groupId}/users
          method: post
          cors: true
  
  # UpdateUser:
  #   handler: users/update.handler
  #   name: ${opt:stage, self:provider.stage}-Users-Update
  #   events:
  #     - http:
  #         path: users/{userId}
  #         method: put
  #         cors: true

resources:

  Resources:

    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: GroupCode
            KeySchema:
              - AttributeName: groupId
                KeyType: HASH
              - AttributeName: code
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:

    GroupsTable:
      Description: Name of the Groups table for the ${opt:stage, self:provider.stage} stage
      Value: { Ref: GroupsTable }
      Export:
        Name: ${opt:stage, self:provider.stage}-GroupsTable
