service: santaSwap-serverless

provider:
  name: aws
  runtime: nodejs4.3
  stage: Local
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    GROUPS_TABLE: { Ref: GroupsTable }
    GROUPS_TABLE_CODE_INDEX: GroupCode
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  
  createAndJoin:
    handler: groups/createAndJoin.handler
    events:
      - http:
          path: groups
          method: post
          cors: true
  
  update:
    handler: groups/updateGroup.handler
    events:
      - http:
          path: groups/{groupId}
          method: put
          cors: true
  
  listByUser:
    handler: groups/listByUser.handler
    events:
      - http:
          path: users/{userId}/groups
          method: get
          cors: true
  
  get:
    handler: groups/get.handler
    events:
      - http:
          path: groups/{groupId}
          method: get
          cors: true
  
  query:
    handler: groups/query.handler
    events:
      - http:
          path: groups
          method: get
          cors: true
  
  join:
    handler: groups/join.handler
    events:
      - http:
          path: groups/{groupId}/users
          method: post
          cors: true
  
  # UpdateUser:
  #   handler: users/update.handler
  #   name: ${opt:stage, self:provider.stage}-Users-Update
  #   events:
  #     - http:
  #         path: users/{userId}
  #         method: put
  #         cors: true

resources:

  Resources:

    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GROUPS_TABLE_CODE_INDEX}
            KeySchema:
              - AttributeName: code
                KeyType: HASH
              - AttributeName: groupId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:

    GroupsTable:
      Description: Name of the Groups table for the ${opt:stage, self:provider.stage} stage
      Value: { Ref: GroupsTable }
      Export:
        Name: ${opt:stage, self:provider.stage}-GroupsTable
